name: birlestir

on:
  workflow_dispatch:

jobs:
  birlestir:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v4

      - name: Python'u kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: |
          pip install --upgrade pip requests

      - name: m3u_kanal_listesi.txt oluştur
        run: |
          echo "https://ornek.com/list1.m3u" > m3u_kanal_listesi.txt
          echo "https://ornek.com/list2.m3u" >> m3u_kanal_listesi.txt

      - name: Python scriptini çalıştır
        run: python m3u_birlestirici.py
