name: birlestir

on:
  schedule:
    - cron: '0 */1 * * *'  # Her saat başı çalışır
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip requests pytz

      - name: Run M3U birlestirici script
        run: python m3u_birlestirici.py

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add birlesik.m3u
          if [ -f kayit_json/birlesik_links.json ]; then
            git add kayit_json/birlesik_links.json
          fi
          git diff --cached --quiet || git commit -m "Otomatik güncelleme: birlesik dosyalar"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
