name: M3U Birleştirici

on:
  schedule:
    # UTC saatine göre 09, 15 ve 21 → Türkiye saatiyle 12, 18 ve 24
    - cron: '0 9,15,21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  birlestir:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python'u kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bağımlılıkları kur
        run: pip install --upgrade pip requests

      - name: M3U dosyalarını birleştir
        run: python m3u_birlestirici.py

      - name: Commit ve push (eğer değişiklik varsa)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add birlesik.m3u kayit_json/birlesik_links.json
          if git diff --cached --quiet; then
            echo "Değişiklik yok, commit/push yapılmadı."
          else
            git commit -m "Otomatik m3u birleştirme güncellemesi"
            git push
